### ISSUE TITLE
scheduler does not honor DUPEFILTER_CLASS from settings

### ISSUE THREAD

**Issue by mystby** [rolando/scrapy-redis#37]
Here's what we have in original

        dupefilter_cls = load_object(settings['DUPEFILTER_CLASS'])
        dupefilter = dupefilter_cls.from_settings(settings)

in redis version the class name is hardcoded

self.df = RFPDupeFilter(self.server, self.dupefilter_key % {'spider': spider.name})

**Comment by darkrho** [comment]
That's right. It was done in this way to force the use of the redis-based
dupefilter, otherwise the multiple instance of the crawler would not be
able to filter already seen requests.

However, I think `scrapy-redis` should respect the `DUPEFILTER_CLASS` and
point out the use of the redis-based dupefilter. Thanks for bringing that
up.

**Comment by mystby** [comment]
Great, thank you.
I use pyrebloom as a filter and I'm really looking forward for the fix so I don't have to override your classes.

**Comment by chishaku** [comment]
@mystby @rolando 

Is it possible to use a `pyrebloom` dupe filter with multiple crawlers?

**Comment by rolando** [comment]
@chishaku yes, as `pyrebloom` uses redis it seems a good fit for a redis-based distributed crawler.

**Comment by yinzishao** [comment]
@rolando can you share something about how  pyrebloom uses redis?

**Comment by rolando** [comment]
Current release honors the ``DUPEFILTER_CLASS`` setting.
