### ISSUE TITLE
How  to use redis-cluster?

### ISSUE THREAD

**Issue by Rengang** [rolando/scrapy-redis#69]
just support single redis ? now i want use redis cluster , what can i do

**Comment by liihu1n** [comment]
the same to u.

**Comment by mcanonic** [comment]
Is it possible?

**Comment by rolando** [comment]
I haven't used redis cluster myself, and looks like this would need to change the client to use [rediscluster.StrictRedisCluster](https://github.com/Grokzen/redis-py-cluster#usage-example) and support the startup nodes values.

**Comment by mcanonic** [comment]
Yes Rolando. I have tried to modify your code in order to interact with redis-cluster with no much luck. If you have more hints, please let me know. Anyway, thank for your work!

**Comment by fly51** [comment]
What is this?  Why email me?

2017-02-21 

fly5120 



发件人：mcanonic <notifications@github.com>
发送时间：2017-02-21 19:18
主题：Re: [rolando/scrapy-redis] How to use redis-cluster? (#69)
收件人："rolando/scrapy-redis"<scrapy-redis@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Yes Rolando. I have tried to modify your code in order to interact with redis-cluster with no much luck. If you have more hints, please let me know. Anyway, thank for your work!

**Comment by rolando** [comment]
@fly51 You are subscribed to this issue. To unsubscribe click on the `Unsubscribe` button in the sidebar.

**Comment by hustshawn** [comment]
So did you planed to support the redis cluster?

**Comment by szthanatos** [comment]
same question, & may I know when will this be possible?
