### ISSUE TITLE
Is there any way to set priority on start_urls ?

### ISSUE THREAD

**Issue by kekeadou** [rolando/scrapy-redis#90]
I need to set priority on start_urls and pass the priority to requests they generate.But after I read the source code, I think I should overwrite start_requests() method to use SortedSet instead of Set.
My problem is that is there any other way to do this? Why do we use set for start_urls but sorted set for requests?

**Comment by rolando** [comment]
`start_urls` started as a simple FIFO queue. Then someone needed to discard duplicates in the start urls queue and therefore set support was added.

Yes, you need to overwrite the `start_requests` (this method https://github.com/rolando/scrapy-redis/blob/v0.6.8/src/scrapy_redis/spiders.py#L75) method to support a priority queue (sorted set). You can also support a complex object (json-like) instead of a single string to pass additional parameters (like priority) and then pass that priority to the further requests. The usual approach in scrapy is to use `request.meta["parameter"] = value` before returning the request and in the callback read it as `response.meta["parameter"]`.

**Comment by kekeadou** [comment]
Many thanks:)

**Comment by liangWenPeng** [comment]
I have overwrited the start_requests and set SCHEDULER_PERSIST=True,and the redis queues is not empty, then when spider open ,where is the first requesrt  from ? start_requests or  redis queues?
